/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetsRouteImport } from './routes/vets'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiseaseRouteImport } from './routes/disease'
import { Route as IndexRouteImport } from './routes/index'

const VetsRoute = VetsRouteImport.update({
  id: '/vets',
  path: '/vets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseRoute = DiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disease': typeof DiseaseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/vets': typeof VetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disease': typeof DiseaseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/vets': typeof VetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disease': typeof DiseaseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/vets': typeof VetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disease'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/planner'
    | '/profile'
    | '/vets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disease'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/planner'
    | '/profile'
    | '/vets'
  id:
    | '__root__'
    | '/'
    | '/disease'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/planner'
    | '/profile'
    | '/vets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiseaseRoute: typeof DiseaseRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  VetsRoute: typeof VetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vets': {
      id: '/vets'
      path: '/vets'
      fullPath: '/vets'
      preLoaderRoute: typeof VetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease': {
      id: '/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof DiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiseaseRoute: DiseaseRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  VetsRoute: VetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
